# columns eliminated from footy stats raw data
FS_UNUSED_COLS = [
    "date_GMT",
    "status",
    "attendance",
    "referee",
    "Game Week",
    "stadium_name",
    "home_team_goal_count",
    "away_team_goal_count",
    "home_team_goal_timings",
    "away_team_goal_timings",
    "home_team_first_half_cards",
    "away_team_first_half_cards",
    "home_team_second_half_cards",
    "away_team_second_half_cards",
    "Pre-Match PPG (Home)",
    "Pre-Match PPG (Away)",
    "home_ppg",
    "away_ppg",
    "Home Team Pre-Match xG",
    "Away Team Pre-Match xG",
    "average_goals_per_match_pre_match",
    "over_15_percentage_pre_match",
    "over_25_percentage_pre_match",
    "over_35_percentage_pre_match",
    "over_45_percentage_pre_match",
    "over_15_HT_FHG_percentage_pre_match",
    "over_05_HT_FHG_percentage_pre_match",
    "over_15_2HG_percentage_pre_match",
    "over_05_2HG_percentage_pre_match",
    "btts_percentage_pre_match",
    "average_corners_per_match_pre_match",
    "average_cards_per_match_pre_match",
    "odds_ft_home_team_win",
    "odds_ft_draw",
    "odds_ft_away_team_win",
    "odds_ft_over15",
    "odds_ft_over25",
    "odds_ft_over35",
    "odds_ft_over45",
    "odds_btts_yes",
    "odds_btts_no",
    "timestamp",
    "home_team_name",
    "away_team_name",
    "total_goal_count",
    "total_goals_at_half_time",
    "home_team_goal_count_half_time",
    "away_team_goal_count_half_time",
    "home_team_shots_off_target",
    "away_team_shots_off_target",
]

#### ELO adjustments -- columns
elo_ind = [
    "game_id",
    "world_cup",
    "continent",
    "wc_quali",
    "cont_quali",
    "nat_league",
    "friendly",
    "other_comp",
]
elo_t1 = [
    "t1",
    "t2",
    "t1_venue_status",
    "pre_match_elo_t1",
    "pre_match_elo_t2",
    "t1_score",
    "t2_score",
    "t1_outcome",
]
elo_t2 = [
    "t2",
    "t1",
    "t2_venue_status",
    "pre_match_elo_t2",
    "pre_match_elo_t1",
    "t2_score",
    "t1_score",
    "t2_outcome",
]
elo_cols = [
    "team",
    "opponent",
    "home_away_neutral",
    "pre_match_elo",
    "opponent_pm_elo",
    "goals_scored",
    "goals_conceded",
    "outcome",
]


#### FS adjustments -- columns
fs_ind = ["game_id"]
fs_t1 = [
    "home_team",
    "home_team_possession",
    "home_team_shots",
    "away_team_shots",
    "home_team_shots_on_target",
    "away_team_shots_on_target",
    "home_team_xg",
    "away_team_xg",
    "home_team_corner_count",
    "away_team_corner_count",
    "home_team_yellow_cards",
    "away_team_yellow_cards",
    "home_team_red_cards",
    "away_team_red_cards",
    "home_team_fouls",
    "away_team_fouls",
]
fs_t2 = [
    "away_team",
    "away_team_possession",
    "away_team_shots",
    "home_team_shots",
    "away_team_shots_on_target",
    "home_team_shots_on_target",
    "away_team_xg",
    "home_team_xg",
    "away_team_corner_count",
    "home_team_corner_count",
    "away_team_yellow_cards",
    "home_team_yellow_cards",
    "away_team_red_cards",
    "home_team_red_cards",
    "away_team_fouls",
    "home_team_fouls",
]
fs_cols = [
    "team",
    "possession",
    "shots",
    "shots_conceded",
    "shots_on_target",
    "shots_on_target_conceded",
    "xg",
    "xg_conceded",
    "corners",
    "corners_conceded",
    "yellow_cards",
    "yellow_cards_drawn",
    "red_cards",
    "red_cards_drawn",
    "fouls",
    "fouls_drawn",
]

LAG_COLS = [
    "pre_match_elo",
    "opponent_pm_elo",
    "goals_scored",
    "goals_conceded",
    "outcome",
    # "home_away_neutral",
    # "world_cup",
    # "continent",
    # "wc_quali",
    # "cont_quali",
    # "nat_league",
    # "friendly",
    # "other_comp",
    # "possession",
    # "shots",
    # "shots_conceded",
    # "shots_on_target",
    # "shots_on_target_conceded",
    # "xg",
    # "xg_conceded",
    # "corners",
    # "corners_conceded",
    # "yellow_cards",
    # "yellow_cards_drawn",
    # "red_cards",
    # "red_cards_drawn",
    # "fouls",
    # "fouls_drawn",
    # "team_value_opponent",
    # "att_value_opponent",
    # "mid_value_opponent",
    # "def_value_opponent",
    # "gk_value_opponent",
    # "start_gk_value_opponent",
    # "start_def_value_opponent",
    # "start_mid_value_opponent",
    # "start_att_value_opponent",
    # "best_player_opponent",
    # "worst_player_opponent",
    # "value_std_opponent",
    # "average_age_opponent",
]

HIST_COLS = [
    "goals_scored",
    "goals_conceded",
    # "outcome",
    # "opponent_pm_elo",
    "xg",
    "xg_conceded",
    # "shots",
    # "shots_on_target",
    # "shots_conceded",
    # "shots_on_target_conceded",
    # "possession",
]
